### ISSUE TITLE
Send Proxy-Info back to client in HTTP Header.

### ISSUE THREAD

**Issue by bluet** [bluet/proxybroker2#1]
I've added a feature for removing proxy from queue by client (starting from https://github.com/constverum/ProxyBroker/pull/161/commits/c9e58a0b366ed6f7fca3691e87db513566e6d364), but it would still be useless if clients are not able to know which proxy are they using.

If we can add a `X-Proxy-Info` header in response to client, it would make life much easier.

example: `X-Proxy-Info: proxy1.localtest.me:8080`

**Comment by synchronizing** [comment]
Client and (chosen) proxy become connected via the `server._stream` function. 

https://github.com/bluet/proxybroker2/blob/667b6ce6c2c2c6793d8602ea690804b7b8da7c1c/proxybroker/server.py#L246-L258

The `server._stream` just streams the the proxy's and clients request via their transporters. 

https://github.com/bluet/proxybroker2/blob/667b6ce6c2c2c6793d8602ea690804b7b8da7c1c/proxybroker/server.py#L328-L342

The issue with the current implementation is that it requires parsing the response from the proxies, and then injecting a custom header. My thought to this was to create a man-in-the-middle module that allows extensive extensionality; i.e. add headers, check validity of responses from previous (known) correct responses, etc.

**Comment by bluet** [comment]
@synchronizing totally agree with you.

I'm thinking about maybe read few lines from resp (like, two or three lines, just to make sure there are data in http header), send those two lines + `X-Proxy-Info`to client, and then connect two streams after this.

Or maybe even just inject the `X-Proxy-Info` here at https://github.com/bluet/proxybroker2/blob/667b6ce6c2c2c6793d8602ea690804b7b8da7c1c/proxybroker/server.py#L341 to satisfy current needs.

**Comment by bluet** [comment]
@synchronizing I mean, as a tmp solution for now.

**Comment by synchronizing** [comment]
Makes sense, and I think totally possible. Like I said, however, injecting this header into HTTPS requests would not work from my current understanding of SSL/TLS. After the initial `CONNECT` statement by the client the server _only_ replies with encrypted responses that only the client has access to. 

On the separate project I'm currently trying to find a decent way to parse and modify raw HTTP requests/responses without having to do it manually. Currently scorwing to find any good modules to do this, so I'll let you know if I find anything decent. For the temporary solution, however, I think it should be easy enough to plop `X-Proxy-Info` into the HTTP response headers.

**Comment by bluet** [comment]
@synchronizing  I managed to inject X-Proxy-Info after HTTP status.
For HTTPS after connection established (before SSL), but not sure if clients are able to check it...

**Comment by synchronizing** [comment]
Found an awesome module for header manipulation. Posting it here for reference. https://github.com/Ousret/kiss-headers

**Comment by synchronizing** [comment]
@bluet Currently making a good amount of progress in the new project, but I had to branch out a specific portion. You will likely find it useful for this specific issue. https://github.com/synchronizing/httpsuite

**Comment by bluet** [comment]
@synchronizing any possibility to integrate it to solve current https issue in proxybroker2?

**Comment by synchronizing** [comment]
Working on that, but that is a separate issue all together. Your specific question is the one I asked myself a few years back and tried to solve it with https://github.com/constverum/ProxyBroker/pull/129. `httpsuite` was a branch out of my re-write of ProxyBroker, which I've already added support for this -- I'll be posting it hopefully within the next month or two.

**Comment by bluet** [comment]
@synchronizing I just realized that I forgot to invite you to become collaborator.... Invitation just sent... lol
