### ISSUE TITLE
Executing find command with any parameters throws "AttributeError: 'TransportSocket' object has no attribute 'close'"

### ISSUE THREAD

**Issue by ziloka** [bluet/proxybroker2#111]
**Describe the bug**
Using python 3.11, this error is thrown if using the program at all. (as a library or command line app)

**To Reproduce**
1. Install proxybroker (the current HEAD)
```sh
pip install git+https://github.com/bluet/proxybroker2.git@d6736a3f7940c10dd64a1dcdb5152e00bc92ea23
```
2. run find command
```sh
proxybroker find --types HTTP HTTPS --lvl High --countries US --strict -l 10
```
3. see Error "AttributeError: 'TransportSocket' object has no attribute 'close'"

**Expected behavior**
Only see the results, and not errors

**Screenshots**
![image](https://user-images.githubusercontent.com/50429450/200145936-3da70cae-6bfa-40ab-9da3-14aa2d8f23c2.png)

**Desktop (please complete the following information):**
 - OS: Debian Linux 11
 - Version commit d6736a3f7940c10dd64a1dcdb5152e00bc92ea23

**Additional context**
N/A

**Comment by ziloka** [comment]
This seems to just be a python 3.11 error.
This doesn't appear on python 3.12.0a1

**Comment by afunTW** [comment]
We test from Python 3.8 to Python 3.10 only, welcome to contribute to support the further version.

**Comment by bluet** [comment]
@ziloka @afunTW Do you think if it's OK to just ignore 3.11 support (and wait for 3.12)?

**Comment by ziloka** [comment]
> @ziloka @afunTW Do you think if it's OK to just ignore 3.11 support (and wait for 3.12)?

I think it would be okay because python 3.11 just seems like a wonky version. they seemed to remove a socket method for no reason and then added it for 3.12
