### ISSUE TITLE
ERROR: Could not build wheels for pycares, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by denisxab** [bluet/proxybroker2#112]
╰─➤  pip install -U git+https://github.com/bluet/proxybroker2.git                                             130 ↵
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/bluet/proxybroker2.git
  Cloning https://github.com/bluet/proxybroker2.git to /tmp/pip-req-build-7fuwlfvf
  Running command git clone --filter=blob:none --quiet https://github.com/bluet/proxybroker2.git /tmp/pip-req-build-7fuwlfvf
  Resolved https://github.com/bluet/proxybroker2.git to commit d6736a3f7940c10dd64a1dcdb5152e00bc92ea23
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiohttp<4.0.0,>=3.8.1
  Using cached aiohttp-3.8.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
Requirement already satisfied: attrs<23.0.0,>=22.1.0 in /home/denis/.local/lib/python3.11/site-packages (from proxybroker==2.0.0a4) (22.1.0)
Collecting cachetools<6.0.0,>=5.2.0
  Using cached cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting maxminddb<3.0.0,>=2.2.0
  Using cached maxminddb-2.2.0-py2.py3-none-any.whl
Collecting click<9.0.0,>=8.1.3
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting aiodns<4.0.0,>=3.0.0
  Using cached aiodns-3.0.0-py3-none-any.whl (5.0 kB)
Collecting pycares>=4.0.0
  Using cached pycares-4.2.2.tar.gz (825 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /home/denis/.local/lib/python3.11/site-packages (from aiohttp<4.0.0,>=3.8.1->proxybroker==2.0.0a4) (2.1.1)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (117 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.3.3-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (154 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.8.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (278 kB)
Collecting cffi>=1.5.0
  Using cached cffi-1.15.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (462 kB)
Requirement already satisfied: idna>=2.0 in /home/denis/.local/lib/python3.11/site-packages (from yarl<2.0,>=1.0->aiohttp<4.0.0,>=3.8.1->proxybroker==2.0.0a4) (3.4)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Building wheels for collected packages: proxybroker, pycares
  Building wheel for proxybroker (pyproject.toml) ... done
  Created wheel for proxybroker: filename=proxybroker-2.0.0a4-py3-none-any.whl size=1575248 sha256=32d8f6c90278c2dc423850ba30256c195fddbc7fb3f2b7ebef826f6645dc343b
  Stored in directory: /tmp/pip-ephem-wheel-cache-si32e5vm/wheels/ed/a1/34/283a41bc42be90a139ef9f1899889e9e8d1f90f324f2f0c596
  Building wheel for pycares (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pycares (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.11
      creating build/lib.linux-x86_64-3.11/pycares
      copying src/pycares/_version.py -> build/lib.linux-x86_64-3.11/pycares
      copying src/pycares/__main__.py -> build/lib.linux-x86_64-3.11/pycares
      copying src/pycares/errno.py -> build/lib.linux-x86_64-3.11/pycares
      copying src/pycares/utils.py -> build/lib.linux-x86_64-3.11/pycares
      copying src/pycares/__init__.py -> build/lib.linux-x86_64-3.11/pycares
      running build_ext
      creating build/temp.linux-x86_64-3.11
      creating build/temp.linux-x86_64-3.11/build
      creating build/temp.linux-x86_64-3.11/build/temp.linux-x86_64-3.11
      creating build/temp.linux-x86_64-3.11/deps
      creating build/temp.linux-x86_64-3.11/deps/c-ares
      creating build/temp.linux-x86_64-3.11/deps/c-ares/src
      creating build/temp.linux-x86_64-3.11/deps/c-ares/src/lib
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DCARES_STATICLIB=1 -Ideps/build-config/config_linux -Ideps/build-config/include -Ideps/c-ares/include -I/usr/include/python3.11 -c build/temp.linux-x86_64-3.11/_cares.c -o build/temp.linux-x86_64-3.11/build/temp.linux-x86_64-3.11/_cares.o
      build/temp.linux-x86_64-3.11/_cares.c:50:14: fatal error: pyconfig.h: No such file or directory
         50 | #    include <pyconfig.h>
            |              ^~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycares
Successfully built proxybroker
Failed to build pycares
ERROR: Could not build wheels for pycares, which is required to install pyproject.toml-based projects

**Comment by ziloka** [comment]
You probably need to install the pycares package for your operating system? 
eg, Ubuntu: `sudo apt-get install python3-pycares`
