### ISSUE TITLE
Fix latest build arch64 support

### ISSUE THREAD

**Issue by stratbasher** [bluet/proxybroker2#117]
**Describe the bug**
Latest build doesn't work with arch64, there is only an amd64 tag.

**To Reproduce**
1. From an arch system, "export DOCKER_DEFAULT_PLATFORM=linux/arm64"
2. Run "docker-compose up proxybroker2" with appropriate docker-compose.yml file
4. "WARNING: image with reference bluet/proxybroker2 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64
5. When running, "exec /usr/local/bin/python: exec format error"

**Expected behavior**
When pulling / building from Dockerhub, arm64 support

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 22.04.1 LTS

**Comment by stratbasher** [comment]
> arch64

**Comment by stratbasher** [comment]
As a note, running with image: bluet/proxybroker2:v2.0.0-alpha4 works.

**Comment by bluet** [comment]
@stratbasher yup sorry we don't have a `stable` tag for proxybroker2 yet. the `latest` tag is an autobuild.

Porting to Python3.10+ is moving slowly and we need more volunteers to join. :joy:
