### ISSUE TITLE
Docker serve not working, but ran pip working ok

### ISSUE THREAD

**Issue by j4uonline** [bluet/proxybroker2#127]
System: ubuntu 20.04 & Centos 7.9
Python: 3.9.0

Comand: docker run -it --rm bluet/proxybroker2 serve --host 127.0.0.1 --port 8888 --types HTTP HTTPS --lvl High --min-queue 5

Logs:
/usr/local/lib/python3.9/asyncio/events.py:80: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._context.run(self._callback, *self._args)
Server started at http://127.0.0.1:8888
/usr/local/lib/python3.9/asyncio/trsock.py:20: DeprecationWarning: Using send() method on sockets returned from get_extra_info('socket') will be prohibited in asyncio 3.9. Please report your use case to bugs.python.org.
  warnings.warn(
DeprecationWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.9/asyncio/trsock.py:20: DeprecationWarning: Using recv() method on sockets returned from get_extra_info('socket') will be prohibited in asyncio 3.9. Please report your use case to bugs.python.org.
  warnings.warn(
DeprecationWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.9/asyncio/trsock.py:20: DeprecationWarning: Using close() method on sockets returned from get_extra_info('socket') will be prohibited in asyncio 3.9. Please report your use case to bugs.python.org.
  warnings.warn(
DeprecationWarning: Enable tracemalloc to get the object allocation traceback

I check port open with command: “netstat -lpnt”
And don’t see it had open 8888

But a test with command:
proxybroker serve --host 127.0.0.1 --port 8888 --types HTTP HTTPS --lvl High --min-queue 5

And it working ok, had port open 8888
“127.0.0.1:8888”

What happen with docker?

**Comment by bluet** [comment]
hi @j4uonline , may I know how did you install the proxybroker?

**Comment by j4uonline** [comment]
> hi @j4uonline , may I know how did you install the proxybroker?

I use: docker pull bluet/proxybroker2

**Comment by theaidem** [comment]
@j4uonline try this for start docker container
`docker run --rm -p 8888:8888 bluet/proxybroker2 --log CRITICAL serve --host 127.0.0.1 --port 8888 --types HTTP HTTPS --lvl High --min-queue 5`

**Comment by j4uonline** [comment]
> @j4uonline try this for start docker container `docker run --rm -p 8888:8888 bluet/proxybroker2 --log CRITICAL serve --host 127.0.0.1 --port 8888 --types HTTP HTTPS --lvl High --min-queue 5`

thank you, it working
