### ISSUE TITLE
How to convert this ProxyBroker script to exe?

### ISSUE THREAD

**Issue by paolosezart** [bluet/proxybroker2#31]
How to convert this script to exe?
I would like to get a Windows binary to search for proxies. So that I could run from a flash drive.
Very good script.
But I can't compile. Or maybe you already have a compiled version?
I've tried auto-py-to-exe but it doesn't work.Thanks

**Comment by bluet** [comment]
@paolosezart actually I don't know. I've been in pure Linux (Ubuntu) environments for more than a decade.

If you know how to do that, can also please let others know by adding a section in README :-)

**Comment by bluet** [comment]
added instructions in README.md in #95
